const ACTION_TYPE = {
    REQUEST_LOADING: 'REQUEST_LOADING',
    LOGIN_START: 'LOGIN_START',
    LOGIN_FAILED: 'USER_LOGIN_FAIL',
    LOGIN_FINISHED: 'LOGIN_FINISHED',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    SIGNUP_STOP: 'SIGNUP_STOP',
    MESSAGE: 'MESSAGE',


};
export default ACTION_TYPE;
