const ACTION_TYPE = {
    REQUEST_LOADING: 'REQUEST_LOADING',
    LOGIN_SUCCESSFUL: 'LOGIN_USER',
    LOGIN_FAILED: 'USER_LOGIN_FAIL',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    SIGNUP_STOP: 'SIGNUP_STOP',
    MESSAGE: 'MESSAGE',


};
export default ACTION_TYPE;
